PREFIX = "scheme"
OUTPUT_PATH = "./output"

TARGET_OVERLAP = 0
STEP_DISTANCE = 11
AMPLICON_SIZE_MIN = 380
AMPLICON_SIZE_MAX = 420

PRIMER_SIZE_MIN = 22
PRIMER_SIZE_MAX = 30
PRIMER_OPT_SIZE = PRIMER_SIZE_MIN

PRIMER_OPT_TM = 61.5
PRIMER_WT_TM_GT = 1.0
PRIMER_WT_TM_LT = 1.0
PRIMER_MIN_TM = 60
PRIMER_MAX_TM = 63
PRIMER_WT_SIZE_GT = 1.0
PRIMER_WT_SIZE_LT = 1.0
PRIMER_OPT_GC_PERCENT = 50.0
PRIMER_WT_GC_PERCENT_GT = 0.0
PRIMER_WT_GC_PERCENT_LT = 0.0
PRIMER_MIN_GC = 30
PRIMER_MAX_GC = 55
PRIMER_MAX_HAIRPIN_TH = 50
PRIMER_MAX_HOMO = 5

PRIMER_MAX_MISMATCHES = 2
PRIMER_MISMATCH_PENALTIES = [3, 2, 1]  # distance from 3', last is default

MV_CONC = 50
DV_CONC = 1.5
DNA_CONC = 15
DNTP_CONC = 0.2
TEMP_C = 0
HETERODIMER_DG_THRESHOLD = -24
