[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "primalscheme"
author = "Josh Quick"
author-email = "j.quick@bham.ac.uk"
maintainer = "Andrew Smith"
maintainer-email = "andysmith.d@gmail.com"
home-page = "https://github.com/aresti/primalscheme"

requires = [
    "biopython>=1,<2",
    "click==8.1.3",
    "parasail==1.2",
    "primer3-py>=0,<1",
    "progress==1.5",
    "reportlab>=3,<4",
]
requires-python = ">=3.7,<4"

description-file = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[tool.flit.scripts]
primalscheme = "primalscheme.cli:cli"

[tool.flit.metadata.requires-extra]
dev = ["pre-commit"]
test = [
    "pytest >=2.7.3",
    "pytest-cov",
]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py36, py37, py38

[testenv]
deps = pytest >= 3.0.0, <4
commands = pytest
"""
